### ISSUE TITLE
Clock_watchdog_timeout

### ISSUE THREAD

**Issue by AmirRezaei** [lowleveldesign/process-governor#31]
Got the error "clock_watchdog_timeout" after running CPU incentive process.
With parameters --cpu=16. Having 32 CPU in total on AMD 5950X.

**Comment by lowleveldesign** [comment]
@AmirRezaei, I'm afraid I can do nothing about this error. Process Governor uses the system job API to apply the CPU limits. I do not install any drivers or modify system processes in any way. Based on [the error description](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x101---clock-watchdog-timeout), this issue looks to me more like a system/hardware error rather than something I could fix in the procgov code.
