### ISSUE TITLE
Make bitness explicit in EXE name

### ISSUE THREAD

**Issue by Korporal** [lowleveldesign/process-governor#34]
Hi,

This is just a small suggestion. The 32 bit build is named "procgov.exe" and the 64 bit build is named "procgov64.exe" I inadvertently just ran "procgov" to limit memory use and struggled to understand the "32 bit" error, suspecting my service had been built for 32-bit platform. I eventually scanned your source and understood.

I suggest you name the 32 bit build as "procgov32.exe" and the 64 bit build as "procgov64.exe" - may seem small detail but as soon as a user sees these listed in their installed folder, the bitness aspect is explicit and they will likely not make the error I did!

Thanks

**Comment by lowleveldesign** [comment]
Hi Hugh, great suggestion! Thanks. I will apply the rename in the next release of procgov. I hadn't done it initially because I thought I would, at some point, merge the 64-bit version into procgov.exe, like Sysinternals are doing. But there were always more important things to do and the confusing name stayed 😄
