### ISSUE TITLE
Question: Can you add a function to create a suspended process with procgov?

### ISSUE THREAD

**Issue by AndreyRGW** [lowleveldesign/process-governor#35]
Can you add a function to create a suspended process with procgov? Or add a function to be able to grant privileges to programs, for example - SeLockMemoryPrivilege.

UPD: Or how can I add SeLockMemoryPrivilege privilege to a program? In Process Hacker, you can enable it in the program properties in the token section. But due to the fact that this privilege is enabled after the program is loaded, it just doesn't work.

**Comment by lowleveldesign** [comment]
Hi @AndreyRGW, thanks for the suggestion. I will add an option to grant privileges to a process. Unfortunately, it may take a moment as I'm short on time lately.

**Comment by AndreyRGW** [comment]
> Hi @AndreyRGW, thanks for the suggestion. I will add an option to grant privileges to a process. Unfortunately, it may take a moment as I'm short on time lately.

Oh, thanks, I'll look forward to it!

**Comment by AndreyRGW** [comment]
Sup, how's the development going?

**Comment by lowleveldesign** [comment]
It is completed. I've been struggling with various build issues and I finally migrated the project to .NET 6.0. I hope this won't cause any strange issues. Anyway, 2.10 release contains **--enable-privileges** option. Please make sure the user has a privilege available, otherwise it won't work ([more info](https://github.com/lowleveldesign/process-governor#enable-process-privileges)).
