### ISSUE TITLE
Problem with the registry.

### ISSUE THREAD

**Issue by AndreyRGW** [lowleveldesign/process-governor#38]
Hello, it's me again. 
I tried to run the command: `"procgov64 --install --enable-privileges=SeDebugPrivilege,SeLockMemoryPrivilege largepagetest.exe"`, at first glance it ran successfully but if I go to the registry I see that the debugger only says: `""C:\procgov\procgov64.exe" --nogui --debugger"`. Is this a new bug in .NET 6.0 or is it just not supposed to always run programs with privileges?

**Comment by lowleveldesign** [comment]
Ah, it's a bug I discovered recently and have plans to fix it :) I didn't know you would be using --install as well :) So before the fix is ready, the quick workaround is to manually update the `Debugger` key value in the registry and set it to: `""C:\procgov\procgov64.exe" --nogui --debugger --enable-privileges=SeDebugPrivilege,SeLockMemoryPrivilege"`. It should work as in the command line.
